server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=test,Hello~Filter!!!
      default-filters:
        - AddRequestHeader=origin,gateway
      globalcors:
        add-to-simple-url-handler-mapping: true # 是否开启options询问机制
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些来源
              - "http://localhost:8812"
            allowedMethods: # 允许跨域的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许跨域所携带的请求头信息
            allowedCredentials: true # 是否允许携带cookie
            maxAge: 360000 # options询问机制的缓存时间